version: "3.4"
services:
  server:
    build:
      context: ..
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
      target: webui-server
    depends_on:
      - broker
    environment:
      - BROKER_URL
    ports:
      - "8080:80"
    restart: always
    command: ["sh","-c", "brokerurl=$${BROKER_URL:=mqtt://localhost:9883} && echo '# Using MQTT broker on '$${brokerurl} && sed -i 's|@BROKER_URL_PLACEHOLDER@|'$${brokerurl}'|' /usr/share/nginx/html/main.js && echo '# Open browser on http://localhost:8080' && nginx -g 'daemon off;'"]
  broker:
    build:
      context: ..
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
      target: install-base
    ports:
      - "1883:1883"
      - "9883:9883"
    restart: always
    command: npm run broker
